language: android

# Utilisation du JDK8
jdk:
  - oraclejdk8

android:
  components:
    # Prérequis pour utilisation dernière version Android SDK tools
    - tools
    - platform-tools

    # Build tools requis par le projet
    - build-tools-30.0.3
    # Version du SDK pour compiler le projet
    - android-30

    # Dépôt supplémentaire requis pour avoir support-v4 & appcompat-v7 24.2.1
    - extra-android-m2repository

  licenses:
    - '.+'

# https://gradle.org/install/#manually
before_install:
  - wget https://downloads.gradle.org/distributions/gradle-6.7.1-bin.zip
  - unzip gradle-6.7.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.7.1
  - export PATH=$GRADLE_HOME/bin:$PATH

script:
  - gradle -v
  - gradle build